# Generated by Django 3.2.4 on 2021-06-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_date',
            field=models.DateField(default='UTC'),
        ),
    ]
