# Generated by Django 3.2.4 on 2021-06-14 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_question_q_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
